#!/bin/bash

read -n 1 -r -s -p $'This will mess with the bootloader. Are you sure you want to proceed? Press enter to continue...\n'

if [[ $EUID > 0 ]]
	then echo "ERROR: must be run as root"
	exit
fi

KERNEL_PARAMS="rw quiet loglevel=3"

efibootmgr -b 0000 -B

sleep 3

efibootmgr --disk /dev/nvme0n1 --part 1 --create --label 'Arch Linux' --loader /vmlinuz-linux --unicode 'root=PARTUUID=f86417e6-212e-214d-92eb-e964fa755f15 resume=PARTUUID=a79648a2-aab4-8a48-879f-8b8c74a2d65a '"$KERNEL_PARAMS"' initrd=\amd-ucode.img initrd=\initramfs-linux.img' --verbose
