#!/bin/bash

read -n 1 -r -s -p $'This will mess with the bootloader. Are you sure you want to proceed? Press enter to continue...\n'

if [[ $EUID > 0 ]]
	then echo "ERROR: must be run as root"
	exit
fi

KERNEL_PARAMS="rw nowatchdog"

efibootmgr -b 0000 -B

sleep 3

efibootmgr --disk /dev/sda --part 1 --create --label "Arch Linux" --loader /vmlinuz-linux --unicode 'root=PARTUUID=908d321a-a713-f14d-9884-bf51f54bef18 resume=PARTUUID=089c384e-ab20-614a-825b-5609c2bc10f7 '"$KERNEL_PARAMS"' initrd=\intel-ucode.img initrd=\initramfs-linux.img' --verbose
