#! /bin/sh

bspc config border_width        0
bspc config window_gap         50

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true
bspc config focused_border_color "#E1DFA1"
bspc config active_border_color "#E1DFB7"
bspc config normal_border_color "#E1DFB7"
bspc config presel_border_color "#E1DFB7"
bspc config focused_locked_border_color "#E1DFA1"
bspc config active_locked_border_color "#E1DFB7"
bspc config normal_locked_border_color "#E1DFB7"
bspc config focused_sticky_border_color "#E1DFA1"
bspc config active_sticky_border_color "#E1DFA1"
bspc config normal_sticky_border_color "#E1DFB7"
bspc config focused_private_border_color "#E1DFA1"
bspc config active_private_border_color "#E1DFB7"
bspc config normal_private_border_color "#E1DFB7"
bspc config urgent_border_color "#E1DFA1"


bspc monitor -d I II III IV V VI

bspc rule -a Screenkey manage=off

$HOME/.config/bspwm/Tomoko/captain